### PR TITLE
Refactor whole package to use babel

### PR DESCRIPTION
**Pull request by kevinrambaud**
Following the issue #77 

* added babel (configuration, build and lint)
* updated src and test to use esmodule instead of commonjs
* added .editorconfig

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PRs! I'm getting married this week so I might not be able to review until next week. I promise I won't forget :)

**Comment by kevinrambaud** [comment]
No worries, congrats ! wish you all the best ✌️

**Comment by kevinrambaud** [comment]
hey @shellscape any news ? 😇

**Comment by kevinrambaud** [comment]
up 🙃

**Comment by shellscape** [comment]
@kevinrambaud I've removed myself as an admin for this module based on some actions by the koajs Github org admin, and changes they've mandated for folks who have contributor (and higher) access. Unfortunately one of the other maintainers will have to take this over.

**Comment by kevinrambaud** [comment]
btw @shellscape who will be able to review that ? Who is the current maintainer of this package ?

**Comment by shellscape** [comment]
I'm not sure to be honest. Someone here (https://github.com/orgs/koajs/people) may be able to help.

**Pull request closed without merging**
